# -*- coding: utf-8 -*-
"""Untitled18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-BFtorMuHDY_-ETVGrCvDK7LIlj1aDGu
"""

# Install streamlit if not already installed
try:
    import streamlit as st
except ImportError:
    !pip install streamlit
    import streamlit as st

import requests

# FastAPI Backend URL
BASE_URL = "http://127.0.0.1:8000"

st.set_page_config(
    page_title="Personalized Networking Assistant",
    page_icon="🤝",
    layout="wide"
)

st.title("🤝 Personalized Networking Assistant")

menu = st.sidebar.selectbox(
    "Select Feature",
    [
        "Generate Conversation",
        "Analyze Event",
        "Fact Check",
        "View History",
        "Feedback"
    ]
)

# -------------------------------------------------------
# Generate Conversation
# -------------------------------------------------------

if menu == "Generate Conversation":

    st.header("Generate Personalized Conversation Starters")

    event = st.text_area("Enter Event Description")

    interests = st.text_input(
        "Enter Interests (comma separated)"
    )

    if st.button("Generate"):

        interest_list = [
            item.strip()
            for item in interests.split(",")
            if item.strip()
        ]

        payload = {
            "event_description": event,
            "interests": interest_list
        }

        response = requests.post(
            f"{BASE_URL}/generate-conversation",
            json=payload
        )

        if response.status_code == 200:

            data = response.json()

            st.success("Conversation Generated Successfully")

            st.subheader("Extracted Themes")

            for theme in data["themes"]:
                st.write("•", theme)

            st.subheader("Conversation Suggestions")

            for suggestion in data["suggestions"]:
                st.write("✅", suggestion)

        else:
            st.error("Unable to Generate Conversation")

# -------------------------------------------------------
# Analyze Event
# -------------------------------------------------------

elif menu == "Analyze Event":

    st.header("Analyze Event")

    description = st.text_area("Event Description")

    if st.button("Analyze"):

        payload = {
            "description": description
        }

        response = requests.post(
            f"{BASE_URL}/analyze-event",
            json=payload
        )

        if response.status_code == 200:

            themes = response.json()["themes"]

            st.success("Themes Extracted")

            for theme in themes:
                st.write("•", theme)

        else:
            st.error("Error")

# -------------------------------------------------------
# Fact Check
# -------------------------------------------------------

elif menu == "Fact Check":

    st.header("Wikipedia Fact Checker")

    topic = st.text_input("Enter Topic")

    if st.button("Verify"):

        payload = {
            "topic": topic
        }

        response = requests.post(
            f"{BASE_URL}/fact-check",
            json=payload
        )

        if response.status_code == 200:

            data = response.json()

            st.subheader("Summary")

            st.write(data)

        else:
            st.error("Fact Not Found")

# -------------------------------------------------------
# View History
# -------------------------------------------------------

elif menu == "View History":

    st.header("Conversation History")

    response = requests.get(
        f"{BASE_URL}/history"
    )

    if response.status_code == 200:

        history = response.json()

        for item in history:

            st.markdown("---")

            st.write("### Event")
            st.write(item["event_description"])

            st.write("### Themes")
            st.write(item["themes"])

            st.write("### Suggestions")

            for suggestion in item["suggestions"]:
                st.write("•", suggestion)

    else:
        st.warning("No History Available")

# -------------------------------------------------------
# Feedback
# -------------------------------------------------------

elif menu == "Feedback":

    st.header("Feedback")

    suggestion = st.text_area(
        "Suggestion"
    )

    action = st.radio(
        "Feedback",
        ["like", "dislike"]
    )

    if st.button("Submit Feedback"):

        payload = {
            "suggestion": suggestion,
            "action": action
        }

        response = requests.post(
            f"{BASE_URL}/feedback",
            json=payload
        )

        if response.status_code == 200:
            st.success("Feedback Submitted")

        else:
            st.error("Submission Failed")